### ISSUE TITLE
pod 安装不了。

### ISSUE THREAD

**Issue by leewaycn** [WangGuibin/YogaKitDemo#1]

**Comment by WangGuibin** [comment]
pod升级试试

**Comment by leewaycn** [comment]
pod version 1.5.0 xcode 9.3

**Comment by WangGuibin** [comment]
platform :ios,'8.0'

use_frameworks!
target 'FlexDemo' do
pod 'YogaKit', '~> 1.6.0'
end 

我的可以啊, 你是不是没有添加use_frameworks!   这个库已经支持swift了
